//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntFrm.MainService.MessagePushService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessagePushService.MqWsSoap")]
    public interface MqWsSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 hostname 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMQ", ReplyAction="*")]
        EntFrm.MainService.MessagePushService.SendMQResponse SendMQ(EntFrm.MainService.MessagePushService.SendMQRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMQ", ReplyAction="*")]
        System.Threading.Tasks.Task<EntFrm.MainService.MessagePushService.SendMQResponse> SendMQAsync(EntFrm.MainService.MessagePushService.SendMQRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 hostname 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnilysisMQ", ReplyAction="*")]
        EntFrm.MainService.MessagePushService.AnilysisMQResponse AnilysisMQ(EntFrm.MainService.MessagePushService.AnilysisMQRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnilysisMQ", ReplyAction="*")]
        System.Threading.Tasks.Task<EntFrm.MainService.MessagePushService.AnilysisMQResponse> AnilysisMQAsync(EntFrm.MainService.MessagePushService.AnilysisMQRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMQRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMQ", Namespace="http://tempuri.org/", Order=0)]
        public EntFrm.MainService.MessagePushService.SendMQRequestBody Body;
        
        public SendMQRequest() {
        }
        
        public SendMQRequest(EntFrm.MainService.MessagePushService.SendMQRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMQRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hostname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string channel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string queueManager;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string qManager;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int port;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MSH6;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MSH2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string MSH1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string MSH3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string MSH4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string MSH5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string MSH7;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string MSH8;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string MSH9;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string xml;
        
        public SendMQRequestBody() {
        }
        
        public SendMQRequestBody(string hostname, string channel, string queueManager, string qManager, int port, string MSH6, string MSH2, string MSH1, string MSH3, string MSH4, string MSH5, string MSH7, string MSH8, string MSH9, string xml) {
            this.hostname = hostname;
            this.channel = channel;
            this.queueManager = queueManager;
            this.qManager = qManager;
            this.port = port;
            this.MSH6 = MSH6;
            this.MSH2 = MSH2;
            this.MSH1 = MSH1;
            this.MSH3 = MSH3;
            this.MSH4 = MSH4;
            this.MSH5 = MSH5;
            this.MSH7 = MSH7;
            this.MSH8 = MSH8;
            this.MSH9 = MSH9;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMQResponse", Namespace="http://tempuri.org/", Order=0)]
        public EntFrm.MainService.MessagePushService.SendMQResponseBody Body;
        
        public SendMQResponse() {
        }
        
        public SendMQResponse(EntFrm.MainService.MessagePushService.SendMQResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMQResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMQResult;
        
        public SendMQResponseBody() {
        }
        
        public SendMQResponseBody(int SendMQResult) {
            this.SendMQResult = SendMQResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnilysisMQRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnilysisMQ", Namespace="http://tempuri.org/", Order=0)]
        public EntFrm.MainService.MessagePushService.AnilysisMQRequestBody Body;
        
        public AnilysisMQRequest() {
        }
        
        public AnilysisMQRequest(EntFrm.MainService.MessagePushService.AnilysisMQRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnilysisMQRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hostname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string channel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string queueManager;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string qManager;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int port;
        
        public AnilysisMQRequestBody() {
        }
        
        public AnilysisMQRequestBody(string hostname, string channel, string queueManager, string qManager, int port) {
            this.hostname = hostname;
            this.channel = channel;
            this.queueManager = queueManager;
            this.qManager = qManager;
            this.port = port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnilysisMQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnilysisMQResponse", Namespace="http://tempuri.org/", Order=0)]
        public EntFrm.MainService.MessagePushService.AnilysisMQResponseBody Body;
        
        public AnilysisMQResponse() {
        }
        
        public AnilysisMQResponse(EntFrm.MainService.MessagePushService.AnilysisMQResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnilysisMQResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnilysisMQResult;
        
        public AnilysisMQResponseBody() {
        }
        
        public AnilysisMQResponseBody(string AnilysisMQResult) {
            this.AnilysisMQResult = AnilysisMQResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MqWsSoapChannel : EntFrm.MainService.MessagePushService.MqWsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MqWsSoapClient : System.ServiceModel.ClientBase<EntFrm.MainService.MessagePushService.MqWsSoap>, EntFrm.MainService.MessagePushService.MqWsSoap {
        
        public MqWsSoapClient() {
        }
        
        public MqWsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MqWsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MqWsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MqWsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntFrm.MainService.MessagePushService.SendMQResponse EntFrm.MainService.MessagePushService.MqWsSoap.SendMQ(EntFrm.MainService.MessagePushService.SendMQRequest request) {
            return base.Channel.SendMQ(request);
        }
        
        public int SendMQ(string hostname, string channel, string queueManager, string qManager, int port, string MSH6, string MSH2, string MSH1, string MSH3, string MSH4, string MSH5, string MSH7, string MSH8, string MSH9, string xml) {
            EntFrm.MainService.MessagePushService.SendMQRequest inValue = new EntFrm.MainService.MessagePushService.SendMQRequest();
            inValue.Body = new EntFrm.MainService.MessagePushService.SendMQRequestBody();
            inValue.Body.hostname = hostname;
            inValue.Body.channel = channel;
            inValue.Body.queueManager = queueManager;
            inValue.Body.qManager = qManager;
            inValue.Body.port = port;
            inValue.Body.MSH6 = MSH6;
            inValue.Body.MSH2 = MSH2;
            inValue.Body.MSH1 = MSH1;
            inValue.Body.MSH3 = MSH3;
            inValue.Body.MSH4 = MSH4;
            inValue.Body.MSH5 = MSH5;
            inValue.Body.MSH7 = MSH7;
            inValue.Body.MSH8 = MSH8;
            inValue.Body.MSH9 = MSH9;
            inValue.Body.xml = xml;
            EntFrm.MainService.MessagePushService.SendMQResponse retVal = ((EntFrm.MainService.MessagePushService.MqWsSoap)(this)).SendMQ(inValue);
            return retVal.Body.SendMQResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntFrm.MainService.MessagePushService.SendMQResponse> EntFrm.MainService.MessagePushService.MqWsSoap.SendMQAsync(EntFrm.MainService.MessagePushService.SendMQRequest request) {
            return base.Channel.SendMQAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntFrm.MainService.MessagePushService.SendMQResponse> SendMQAsync(string hostname, string channel, string queueManager, string qManager, int port, string MSH6, string MSH2, string MSH1, string MSH3, string MSH4, string MSH5, string MSH7, string MSH8, string MSH9, string xml) {
            EntFrm.MainService.MessagePushService.SendMQRequest inValue = new EntFrm.MainService.MessagePushService.SendMQRequest();
            inValue.Body = new EntFrm.MainService.MessagePushService.SendMQRequestBody();
            inValue.Body.hostname = hostname;
            inValue.Body.channel = channel;
            inValue.Body.queueManager = queueManager;
            inValue.Body.qManager = qManager;
            inValue.Body.port = port;
            inValue.Body.MSH6 = MSH6;
            inValue.Body.MSH2 = MSH2;
            inValue.Body.MSH1 = MSH1;
            inValue.Body.MSH3 = MSH3;
            inValue.Body.MSH4 = MSH4;
            inValue.Body.MSH5 = MSH5;
            inValue.Body.MSH7 = MSH7;
            inValue.Body.MSH8 = MSH8;
            inValue.Body.MSH9 = MSH9;
            inValue.Body.xml = xml;
            return ((EntFrm.MainService.MessagePushService.MqWsSoap)(this)).SendMQAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntFrm.MainService.MessagePushService.AnilysisMQResponse EntFrm.MainService.MessagePushService.MqWsSoap.AnilysisMQ(EntFrm.MainService.MessagePushService.AnilysisMQRequest request) {
            return base.Channel.AnilysisMQ(request);
        }
        
        public string AnilysisMQ(string hostname, string channel, string queueManager, string qManager, int port) {
            EntFrm.MainService.MessagePushService.AnilysisMQRequest inValue = new EntFrm.MainService.MessagePushService.AnilysisMQRequest();
            inValue.Body = new EntFrm.MainService.MessagePushService.AnilysisMQRequestBody();
            inValue.Body.hostname = hostname;
            inValue.Body.channel = channel;
            inValue.Body.queueManager = queueManager;
            inValue.Body.qManager = qManager;
            inValue.Body.port = port;
            EntFrm.MainService.MessagePushService.AnilysisMQResponse retVal = ((EntFrm.MainService.MessagePushService.MqWsSoap)(this)).AnilysisMQ(inValue);
            return retVal.Body.AnilysisMQResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntFrm.MainService.MessagePushService.AnilysisMQResponse> EntFrm.MainService.MessagePushService.MqWsSoap.AnilysisMQAsync(EntFrm.MainService.MessagePushService.AnilysisMQRequest request) {
            return base.Channel.AnilysisMQAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntFrm.MainService.MessagePushService.AnilysisMQResponse> AnilysisMQAsync(string hostname, string channel, string queueManager, string qManager, int port) {
            EntFrm.MainService.MessagePushService.AnilysisMQRequest inValue = new EntFrm.MainService.MessagePushService.AnilysisMQRequest();
            inValue.Body = new EntFrm.MainService.MessagePushService.AnilysisMQRequestBody();
            inValue.Body.hostname = hostname;
            inValue.Body.channel = channel;
            inValue.Body.queueManager = queueManager;
            inValue.Body.qManager = qManager;
            inValue.Body.port = port;
            return ((EntFrm.MainService.MessagePushService.MqWsSoap)(this)).AnilysisMQAsync(inValue);
        }
    }
}
