//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntWeb.MedicConsole.RecipeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.iron-tech.cn/", ConfigurationName="RecipeService.HospitalServiceSoap")]
    public interface HospitalServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetBoxInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBoxInfo(string patientid, string windowno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetBoxInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBoxInfoAsync(string patientid, string windowno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetPresNoByXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPresNoByXML(string XMLPresInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetPresNoByXML", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPresNoByXMLAsync(string XMLPresInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetFirmpres", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFirmpres(string patientid, string windowNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetFirmpres", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetFirmpresAsync(string patientid, string windowNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetWindowsNO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetWindowsNO(string patientid, string windowNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetWindowsNO", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetWindowsNOAsync(string patientid, string windowNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetWindowsNOByCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetWindowsNOByCard(string patientid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetWindowsNOByCard", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetWindowsNOByCardAsync(string patientid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/PresBack", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PresBack(string patientid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/PresBack", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PresBackAsync(string patientid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/windowStatusUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string windowStatusUpdate(string yfcode, string windowNo, string openorclose);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/windowStatusUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<string> windowStatusUpdateAsync(string yfcode, string windowNo, string openorclose);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetMedInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMedInfo(string XMLMedInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetMedInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMedInfoAsync(string XMLMedInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetStoreTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetStoreTable(string Machine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iron-tech.cn/GetStoreTable", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetStoreTableAsync(string Machine);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HospitalServiceSoapChannel : EntWeb.MedicConsole.RecipeService.HospitalServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HospitalServiceSoapClient : System.ServiceModel.ClientBase<EntWeb.MedicConsole.RecipeService.HospitalServiceSoap>, EntWeb.MedicConsole.RecipeService.HospitalServiceSoap {
        
        public HospitalServiceSoapClient() {
        }
        
        public HospitalServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HospitalServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string GetBoxInfo(string patientid, string windowno) {
            return base.Channel.GetBoxInfo(patientid, windowno);
        }
        
        public System.Threading.Tasks.Task<string> GetBoxInfoAsync(string patientid, string windowno) {
            return base.Channel.GetBoxInfoAsync(patientid, windowno);
        }
        
        public string GetPresNoByXML(string XMLPresInfo) {
            return base.Channel.GetPresNoByXML(XMLPresInfo);
        }
        
        public System.Threading.Tasks.Task<string> GetPresNoByXMLAsync(string XMLPresInfo) {
            return base.Channel.GetPresNoByXMLAsync(XMLPresInfo);
        }
        
        public string GetFirmpres(string patientid, string windowNo) {
            return base.Channel.GetFirmpres(patientid, windowNo);
        }
        
        public System.Threading.Tasks.Task<string> GetFirmpresAsync(string patientid, string windowNo) {
            return base.Channel.GetFirmpresAsync(patientid, windowNo);
        }
        
        public string GetWindowsNO(string patientid, string windowNo) {
            return base.Channel.GetWindowsNO(patientid, windowNo);
        }
        
        public System.Threading.Tasks.Task<string> GetWindowsNOAsync(string patientid, string windowNo) {
            return base.Channel.GetWindowsNOAsync(patientid, windowNo);
        }
        
        public string GetWindowsNOByCard(string patientid) {
            return base.Channel.GetWindowsNOByCard(patientid);
        }
        
        public System.Threading.Tasks.Task<string> GetWindowsNOByCardAsync(string patientid) {
            return base.Channel.GetWindowsNOByCardAsync(patientid);
        }
        
        public string PresBack(string patientid) {
            return base.Channel.PresBack(patientid);
        }
        
        public System.Threading.Tasks.Task<string> PresBackAsync(string patientid) {
            return base.Channel.PresBackAsync(patientid);
        }
        
        public string windowStatusUpdate(string yfcode, string windowNo, string openorclose) {
            return base.Channel.windowStatusUpdate(yfcode, windowNo, openorclose);
        }
        
        public System.Threading.Tasks.Task<string> windowStatusUpdateAsync(string yfcode, string windowNo, string openorclose) {
            return base.Channel.windowStatusUpdateAsync(yfcode, windowNo, openorclose);
        }
        
        public string GetMedInfo(string XMLMedInfo) {
            return base.Channel.GetMedInfo(XMLMedInfo);
        }
        
        public System.Threading.Tasks.Task<string> GetMedInfoAsync(string XMLMedInfo) {
            return base.Channel.GetMedInfoAsync(XMLMedInfo);
        }
        
        public string GetStoreTable(string Machine) {
            return base.Channel.GetStoreTable(Machine);
        }
        
        public System.Threading.Tasks.Task<string> GetStoreTableAsync(string Machine) {
            return base.Channel.GetStoreTableAsync(Machine);
        }
    }
}
