//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntFrm.ExploreConsole.MessagePackService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.mat.aadata.cn/", ConfigurationName="MessagePackService.MessagePack")]
    public interface MessagePack {
        
        // CODEGEN: 命名空间  的元素名称 action 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EntFrm.ExploreConsole.MessagePackService.getMessageResponse getMessage(EntFrm.ExploreConsole.MessagePackService.getMessage request);
        
        // CODEGEN: 命名空间  的元素名称 action 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EntFrm.ExploreConsole.MessagePackService.getJsonMessageResponse getJsonMessage(EntFrm.ExploreConsole.MessagePackService.getJsonMessage request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EntFrm.ExploreConsole.MessagePackService.sendMessageResponse sendMessage(EntFrm.ExploreConsole.MessagePackService.sendMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessage", Namespace="http://webservice.mat.aadata.cn/", Order=0)]
        public EntFrm.ExploreConsole.MessagePackService.getMessageBody Body;
        
        public getMessage() {
        }
        
        public getMessage(EntFrm.ExploreConsole.MessagePackService.getMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string action;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string condition;
        
        public getMessageBody() {
        }
        
        public getMessageBody(string action, string condition) {
            this.action = action;
            this.condition = condition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessageResponse", Namespace="http://webservice.mat.aadata.cn/", Order=0)]
        public EntFrm.ExploreConsole.MessagePackService.getMessageResponseBody Body;
        
        public getMessageResponse() {
        }
        
        public getMessageResponse(EntFrm.ExploreConsole.MessagePackService.getMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getMessageResponseBody() {
        }
        
        public getMessageResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getJsonMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getJsonMessage", Namespace="http://webservice.mat.aadata.cn/", Order=0)]
        public EntFrm.ExploreConsole.MessagePackService.getJsonMessageBody Body;
        
        public getJsonMessage() {
        }
        
        public getJsonMessage(EntFrm.ExploreConsole.MessagePackService.getJsonMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getJsonMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string action;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string condition;
        
        public getJsonMessageBody() {
        }
        
        public getJsonMessageBody(string action, string condition) {
            this.action = action;
            this.condition = condition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getJsonMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getJsonMessageResponse", Namespace="http://webservice.mat.aadata.cn/", Order=0)]
        public EntFrm.ExploreConsole.MessagePackService.getJsonMessageResponseBody Body;
        
        public getJsonMessageResponse() {
        }
        
        public getJsonMessageResponse(EntFrm.ExploreConsole.MessagePackService.getJsonMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getJsonMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getJsonMessageResponseBody() {
        }
        
        public getJsonMessageResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessage", Namespace="http://webservice.mat.aadata.cn/", Order=0)]
        public EntFrm.ExploreConsole.MessagePackService.sendMessageBody Body;
        
        public sendMessage() {
        }
        
        public sendMessage(EntFrm.ExploreConsole.MessagePackService.sendMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public sendMessageBody() {
        }
        
        public sendMessageBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessageResponse", Namespace="http://webservice.mat.aadata.cn/", Order=0)]
        public EntFrm.ExploreConsole.MessagePackService.sendMessageResponseBody Body;
        
        public sendMessageResponse() {
        }
        
        public sendMessageResponse(EntFrm.ExploreConsole.MessagePackService.sendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sendMessageResponseBody {
        
        public sendMessageResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessagePackChannel : EntFrm.ExploreConsole.MessagePackService.MessagePack, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessagePackClient : System.ServiceModel.ClientBase<EntFrm.ExploreConsole.MessagePackService.MessagePack>, EntFrm.ExploreConsole.MessagePackService.MessagePack {
        
        public MessagePackClient() {
        }
        
        public MessagePackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessagePackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagePackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagePackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntFrm.ExploreConsole.MessagePackService.getMessageResponse EntFrm.ExploreConsole.MessagePackService.MessagePack.getMessage(EntFrm.ExploreConsole.MessagePackService.getMessage request) {
            return base.Channel.getMessage(request);
        }
        
        public string getMessage(string action, string condition) {
            EntFrm.ExploreConsole.MessagePackService.getMessage inValue = new EntFrm.ExploreConsole.MessagePackService.getMessage();
            inValue.Body = new EntFrm.ExploreConsole.MessagePackService.getMessageBody();
            inValue.Body.action = action;
            inValue.Body.condition = condition;
            EntFrm.ExploreConsole.MessagePackService.getMessageResponse retVal = ((EntFrm.ExploreConsole.MessagePackService.MessagePack)(this)).getMessage(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntFrm.ExploreConsole.MessagePackService.getJsonMessageResponse EntFrm.ExploreConsole.MessagePackService.MessagePack.getJsonMessage(EntFrm.ExploreConsole.MessagePackService.getJsonMessage request) {
            return base.Channel.getJsonMessage(request);
        }
        
        public string getJsonMessage(string action, string condition) {
            EntFrm.ExploreConsole.MessagePackService.getJsonMessage inValue = new EntFrm.ExploreConsole.MessagePackService.getJsonMessage();
            inValue.Body = new EntFrm.ExploreConsole.MessagePackService.getJsonMessageBody();
            inValue.Body.action = action;
            inValue.Body.condition = condition;
            EntFrm.ExploreConsole.MessagePackService.getJsonMessageResponse retVal = ((EntFrm.ExploreConsole.MessagePackService.MessagePack)(this)).getJsonMessage(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntFrm.ExploreConsole.MessagePackService.sendMessageResponse EntFrm.ExploreConsole.MessagePackService.MessagePack.sendMessage(EntFrm.ExploreConsole.MessagePackService.sendMessage request) {
            return base.Channel.sendMessage(request);
        }
        
        public void sendMessage(string arg0, string arg1) {
            EntFrm.ExploreConsole.MessagePackService.sendMessage inValue = new EntFrm.ExploreConsole.MessagePackService.sendMessage();
            inValue.Body = new EntFrm.ExploreConsole.MessagePackService.sendMessageBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            EntFrm.ExploreConsole.MessagePackService.sendMessageResponse retVal = ((EntFrm.ExploreConsole.MessagePackService.MessagePack)(this)).sendMessage(inValue);
        }
    }
}
